### PR TITLE
fix #3 Android app crashes

### LINKED ISSUE #3: App crashes in android 10
**Describe the bug**
App crashes in android 10

**To Reproduce**
1. Install app from github actions
2. Open App

**Expected behavior**
Open app

**Smartphone (please complete the following information):**
 - Device: Redme y3
 - OS: Android
 - Version 10

**Additional context**
 - Node: 12
 - React Native: 0.62.2

### PR DESCRIPTION
**Pull request by YajanaRao**
Disabled hermes
Realm does not work with hermes

### CODE REVIEW

File: packages/mobile/src/actions/mediaStore.ts [hunk 1]
```diff
@@ -3,89 +3,107 @@ import groupBy from 'lodash/groupBy';
...
   dispatch: ThunkDispatch<{}, {}, AnyAction>,
 ) => {
-  if (query) {
-    RNAndroidAudioStore.search({searchParam: query})
-      .then((media) => {
-        dispatch({
-          type: 'UPDATE_QUERY',
-          payload: media,
-          // query: query
+  try {
```
Comment (YajanaRao) [inline packages/mobile/src/actions/mediaStore.ts:13]: Try catch may not be working as there is already a catch error in promise

**Review by YajanaRao — COMMENTED** [review]
Satisfied
